"""m2m

Revision ID: 0f7d92e3888c
Revises: 3967e569e6d2
Create Date: 2025-03-16 18:09:32.247307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f7d92e3888c'
down_revision: Union[str, None] = '3967e569e6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats_answers',
    sa.Column('stats_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['stats_id'], ['stats.id'], ),
    sa.PrimaryKeyConstraint('stats_id', 'answer_id')
    )
    op.drop_column('stats', 'correct_answers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('correct_answers', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    op.drop_table('stats_answers')
    # ### end Alembic commands ###
